defaults:
  - base_environment

local: true
batch_size: 2
lstm_batch_size: 2

rir_root: "../datasets/rirs_noises/"
musan_root: "../datasets/musan/"
data_dir: "../datasets/"
sltsstc:
    train_subdir: "slt-sstc"
    dev_subdir: "slt-sstc"
    eval_subdir: "slt-sstc"
    train_protocol: "dev_list_5.csv"
    dev_protocol: "dev_trials_5.csv"
    eval_protocol: "dev_trials_5.csv"
    # Preextracted features protocol files
    preextracted_protocols:
        train_fdlp: "train_list_fdlp.npz"
        dev_fdlp: "dev_list_fdlp.npz"
        test_fdlp: "test_list_fdlp.npz"
        train_mel: "train_list_mel.npz"
        dev_mel: "dev_list_mel.npz"
        test_mel: "test_list_mel.npz"
