defaults:
  - base_environment

local: true
batch_size: 2
lstm_batch_size: 2

rir_root: "../datasets/rirs_noises/"
musan_root: "../datasets/musan/"
data_dir: "../datasets/"
sltsstc:
    train_subdir: "slt-sstc"
    dev_subdir: "slt-sstc"
    eval_subdir: "slt-sstc"
    train_protocol: "dev_list.csv"
    dev_protocol: "test_trials_50k.csv"
    eval_protocol: "test_trials_50k.csv"
