defaults:
  - base_environment

sge: true
batch_size: 16
lstm_batch_size: 4

rir_root: "../datasets/rirs_noises/"
musan_root: "../datasets/musan/"
data_dir: "../datasets/"
sltsstc:
    train_subdir: "slt-sstc"
    dev_subdir: "slt-sstc"
    eval_subdir: "slt-sstc"
    train_protocol: "train_list.csv"
    dev_protocol: "dev_trials_50k.csv"
    eval_protocol: "test_trials.csv"